server:
  http_port: 8080
  grpc_port: 50051

database:
  driver: postgres
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-5432}
  username: ${DB_USER:-postgres}
  password: ${DB_PASSWORD:-root}
  name: ${DB_NAME:-xyz_multifinance}
  ssl_mode: ${DB_SSLMODE:-disable}

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret_key: "your-secret-key"
  expiration: 24h

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"

logging:
  level: "debug"
  encoding: "json"
  output_paths: ["stdout", "logs/app.log"]

i18n:
  default_language: "en"
  available_languages: ["en", "id"]
